workflows:
  ios-workflow:
    name: iOS Workflow ad-hoc
    environment:
      xcode: 14.1
      ios_signing:
        provisioning_profiles:
            - Ad-Hoc profile
        certificates:
            - Codemagic Cert
    scripts:
        - script: xcode-project use-profiles
        - script: flutter packages pub get
        - name: Flutter build ipa and automatic versioning
          script: flutter build ipa 
    artifacts:
        - build/ios/ipa/*.ipa
 
