workflows:
  ios-workflow:
    name: iOS Workflow ad-hoc
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.FutstarzRedBaron.snipe59
        provisioning_profiles:
            - Ad-Hoc profile
        certificates:
            - Codemagic Cert
    scripts:
        - script: xcode-project use-profiles
        - script: flutter packages pub get
        - name: Flutter build ipa and automatic versioning
          script: /
              flutter build ipa --no-sound-null-safety
    artifacts:
        - build/ios/ipa/*.ipa
 
